#!/bin/bash
ub="▄▄▄"
lb="▀▀▀"
let padding=($(tput cols)-24)/2
for i in $(eval echo "{1..$padding}"); do echo -n ' '; done
for x in {30..37}
do
    echo -e -n "\e[${x}m$ub\e[0m"
done
echo ""
for i in $(eval echo "{1..$padding}"); do echo -n ' '; done
for x in {90..97}
do
    echo -e -n "\e[${x}m$lb\e[0m"
done
echo ""
